- name: "{{ ansible_host }}: add dstnat rules"
  # async: 100
  # poll: 5
  ansible.builtin.iptables:
    table: nat
    chain: PREROUTING
    protocol: "{{ prototol_loop_var }}"
    match: "{{ prototol_loop_var }}"
    destination: "{{ vpn_loop_var }}"
    destination_port: "{{ mikrotik_loop_var.port_range }}"
    jump: DNAT
    to_destination: "{{ mikrotik_loop_var.ip }}"
    comment: "declaratively dstnat from {{ vpn_loop_var }}:{{ mikrotik_loop_var.port_range }} to mikrotik{{ mikrotik_loop_var.id }} {{ mikrotik_loop_var.ip }} for {{ prototol_loop_var }} protocol"


