- name: "debug node{{ NODE_ID }}"
  hosts: localhost
  gather_facts: no
  connection: local
  pre_tasks:
    - debug:
        msg: "{{ CONFIG }}"
    - debug:
        msg: "{{ groups['mikrotik'] | map('extract', hostvars, 'ansible_host') | list }}"
